### ISSUE TITLE
how to read the outcome of the test_prgds.py

### ISSUE THREAD

**Issue by xnfei** [aschein/prgds#2]
I tried python tests/test_prgds.py, but the result is a bunch of numbers
May I ask what does the outcome mean?

Using numpy backend.
seed: 7411
29% missing
0
500
1000
1500
2000
2500
3000
3500
4000
4500
0
500
1000
1500
2000
2500
3000
3500
4000
4500

**Comment by aschein** [comment]
All of the tests implement a variation of Geweke testing (see [Roger Grosse's excellent tutorial on Geweke testing](https://lips.cs.princeton.edu/testing-mcmc-code-part-2-integration-tests/)). All of the test scripts for testing models (e.g., `test_prgds.py`) will run this alternative Geweke test and then serialize a [P-P plot](https://en.wikipedia.org/wiki/P%E2%80%93P_plot) for each latent variable. If the test passes, then all of the P-P plots should look like straights (see the attached example).

I've added a bash script that 1) cleans up the `pp_plot` directory , 2) compiles the code (if necessary), 3) runs the test, and then 4) opens up all the P-P plots. To run a test, `cd` to the `src/` directory and then type:

`bash tests/run_test.sh test_prgds.py`

![Pi_KK](https://user-images.githubusercontent.com/765833/75704629-b24db980-5c87-11ea-8181-b14f211a3c36.png)

**Comment by xnfei** [comment]
thanks. Last quesiton: what data did you use in test_prgds.py?
I check the code but haven't found the answer.

**Comment by aschein** [comment]
This test generates synthetic data from the prior and then runs fits the model to the synthetic data. There is no external source of data.

**Comment by xnfei** [comment]
Thank you Aaron, for everthing!
